/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData smile = IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frown = IconData(0xf119, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meh = IconData(0xf11a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grin = IconData(0xf580, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad_tear = IconData(0xf5b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
